// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "codenation/squad-4-aceleradev-fs-florianopolis/entity"
import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// UpdateCustomer provides a mock function with given fields: c
func (_m *Repository) UpdateCustomer(c entity.Customer) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Customer) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
