// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "codenation/squad-4-aceleradev-fs-florianopolis/entity"
import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// UpdateCustomer provides a mock function with given fields: customers
func (_m *Service) UpdateCustomer(customers ...entity.Customer) error {
	_va := make([]interface{}, len(customers))
	for _i := range customers {
		_va[_i] = customers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...entity.Customer) error); ok {
		r0 = rf(customers...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
